In [1]:
import numpy as np
first_trial_cyclist = [10, 15, 17, 26]
second_trial_cyclist = [12, 11, 21, 24]

In [2]:
np_first_trial_cyclist = np.array(first_trial_cyclist)
np_second_trial_cyclist = np.array(second_trial_cyclist)
np_first_trial_cyclist + np_second_trial_cyclist

array([22, 26, 38, 50])

In [3]:
#addition
np.add(45, 20)

65

In [4]:
#subtraction
np.subtract(45, 23)

22

In [8]:
#ndarray multiplication
#create ndarray which contains number of hrs worked for 5 days
#hourly rate is 15 USD
np_daily_wage = np.array([7,9, 13, 8, 11])*15
print (np_daily_wage)

[105 135 195 120 165]


In [9]:
#total earning after 5 days
#use sum method to add all data elements of ndarray
sum(np_daily_wage)

720

In [10]:
#camparison operations
#create ndarray for weekly hrs, 5 consecutive weeks hrs data
np_weekly_hrs = np.array([23, 41, 55, 47, 38])

In [11]:
#week with more than 40 hrs
np_weekly_hrs[np_weekly_hrs>40]

array([41, 55, 47])

In [12]:
#week with more not equals to 40 hrs
np_weekly_hrs[np_weekly_hrs !=40]

array([23, 41, 55, 47, 38])

In [13]:
#logical AND operation
np.logical_and(np_weekly_hrs>20, np_weekly_hrs < 50)

array([ True,  True, False,  True,  True])

In [14]:
#logical NOT operationg
np.logical_not(np_weekly_hrs > 35)

array([ True, False, False, False, False])

In [15]:
#accessing arrays
cyclist_trials = np.array([[10, 15, 17, 26], [12, 11, 21, 24]])

In [16]:
#first trial data
first_trial = cyclist_trials[0]
first_trial

array([10, 15, 17, 26])

In [17]:
#second trial data
second_trial = cyclist_trials[1]
second_trial

array([12, 11, 21, 24])

In [18]:
first_cyclist_firstTrial = cyclist_trials[0][0]
first_cyclist_firstTrial

10

In [19]:
#first cyclist: all trial data User":" to select all the rows of an array
first_cyclist_all_trials = cyclist_trials[:, 0]
first_cyclist_all_trials

array([10, 12])

In [20]:
#slicing
cyclist_trials.shape


(2L, 4L)

In [21]:
two_cyclist_trial_data = cyclist_trials[:, 1:3]
two_cyclist_trial_data

array([[15, 17],
       [11, 21]])

In [25]:
#accessing array elements: Iteration
cyclist_trials = np.array([[10, 15, 17, 26], [12, 11, 21, 24]])
two_cyclist_trial_data = cyclist_trials[:, 1:3]
two_cyclist_trial_data

array([[15, 17],
       [11, 21]])

In [26]:
for iterate_cyclist_trials_data in cyclist_trials:
    print (iterate_cyclist_trials_data)

[10 15 17 26]
[12 11 21 24]


In [27]:
for iterate_two_cyclist_trial_data in two_cyclist_trial_data:
    print (iterate_two_cyclist_trial_data)

[15 17]
[11 21]


In [28]:
#indexing with Boolean Arrays
test_scores = np.array([[83, 71, 57, 63], [54, 68, 81, 45]])
passing_score = test_scores > 60
passing_score

array([[ True,  True, False,  True],
       [False,  True,  True, False]])

In [29]:
#send 'passing score' as an argument to 'test score' object
test_scores[passing_score]

array([83, 71, 63, 68, 81])