In [1]:
import numpy as np

In [2]:
#first NumPy array
first_numpy_array = np.array([1,2,3,4])

In [3]:
#print first array
print first_numpy_array

[1 2 3 4]


In [4]:
#array with zeroes
array_with_zeroes = np.zeros((3,3))
array_with_zeroes

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
#array with empty
array_with_empty = np.empty((2,3))
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
#array with arange method
np_arange = np.arange(12)

In [12]:
print np_arange

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [13]:
#reshape method to change/create array
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
#linspace for linearly (equal) spaced data elements
np_linspce = np.linspace(1,6,5)

In [15]:
print np_linspce

[1.   2.25 3.5  4.75 6.  ]


In [17]:
#One dimensional array
oneD_array=np.arange(15)
print oneD_array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [19]:
#Two dimensional array
TwoD_array = oneD_array.reshape(3,5)
print TwoD_array

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [20]:
#Three dimensional array
ThreeD_array = np.arange(27).reshape(3,3,3)
print ThreeD_array

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
